# Generated by Django 5.2.8 on 2025-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ngo', 'NGO'), ('hotel', 'Hotel / Donor')], max_length=20),
        ),
    ]
