# Generated by Django 5.2.8 on 2026-04-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ngo_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
