# Generated by Django 5.2.8 on 2025-11-17 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('food_items', models.TextField()),
                ('quantity', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('location', models.JSONField()),
                ('quality_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('picked-up', 'Picked up'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
