# Generated by Django 5.2.8 on 2025-11-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
