# Generated by Django 5.2.8 on 2026-04-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='rating_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
